[package]
name = "dbo_csv"
version = "0.1.0-alpha.0"
edition = "2024"
license-file = "LICENSE"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
csv = "1.3"
encoding_rs = "0.8.33"
encoding_rs_rw = "0.4.2"
serde = { version = "1", features = ["derive"]}
thiserror = "2"
